### ISSUE TITLE
Issue with log variable in the Setup

### ISSUE THREAD

**Issue by arvindatmuri** [healenium/healenium-appium#13]
I am seeing an issue while setting this up in my machine,
I have followed the Steps Provided in the Readme file and Once the project is built successfully it by default throws the 'Log' Variable is Unresolved(Throughout the project).

What should i do to fix this log issue?

Please note: I havent done any changes to the Code, i have just downloaded the code and just build the Project.
![image](https://user-images.githubusercontent.com/22560545/96393235-44e89c00-120a-11eb-867e-f1d27b1c413c.png)

**Comment by alxkor** [comment]
You have to add Lombok plugin for your IDE to process `@Slf4j` annotation and to provide logging functionality in **healenium-appium** project. I'll fix documentation.

**Comment by arvindatmuri** [comment]
Hi @alxkor , i could see the Lombok plugin in the build.gradle file. and i have it the imports section as well.
![image](https://user-images.githubusercontent.com/22560545/96594659-97bf7200-1336-11eb-87ca-fd6ce3ebe0c3.png)

As i mentioned earlier, i didnt make any changes to the code, the issue are coming after the build is successful. And IDE is not able to find the variable 'Log' definition within all the imports

**Comment by alxkor** [comment]
Try to check your Project and Lombok Plugin settings. They must be:
![image](https://user-images.githubusercontent.com/4388285/96611954-e1439900-1305-11eb-8d1c-ea0162a75af3.png)
![image](https://user-images.githubusercontent.com/4388285/96612057-ff10fe00-1305-11eb-8377-6c76310fa2dd.png)

**Comment by arvindatmuri** [comment]
Hi @alxkor, Thanks a lot Mate! That worked like Magic.

Also, a request to review the documentation and make it more descriptive please. That would be really Helpful! and You guys are doing the Great job already.
