### ISSUE TITLE
driver wrapper class is reinvoking the android mobile app and findElement is not working.

### ISSUE THREAD

**Issue by aakashr23** [healenium/healenium-appium#18]
Hi Team,

I've tried to integrate Healenium with my appium test by following the steps provided in the Readme.md file. After initializing Appium driver when i tried to add Driverwrapper , my mobile application under test is closing. Also findelement method is not locating the correct xpath and is trying to heal with the following warning message:

Trying to heal...
[ConfigRow1] INFO com.epam.healenium.appium.ProxyMethodHandler - locator.hashCode of By.linkText: //android.widget.Button[@resource-id='android:id/button1'] = 1639377330
[ConfigRow1] WARN com.epam.healenium.appium.ProxyMethodHandler - Healing canceled because no locator data exist.

Please help me with this issue. Thanks in advance.

**Comment by alxkor** [comment]
Hello!

You need to run at least one successful test case before you could heal elements (healenium must store correct locator into backend or file system).

**Comment by aakashr23** [comment]
Hi @alxkor,

I tried running the test case with the unchanged element to store the value as you suggested but the problem is that its unable to locate the unchanged element itself, so the value isn't getting stored. Can you suggest any alternate methods? It would be very helpful.

Thanks and regards,
Aakash.

**Comment by KarthikaRavichandran** [comment]
Hi @alxkor ,

I'm also facing the same issue. Any help on this would be much appreciated.
Thank you.

**Comment by alxkor** [comment]
Hello! Check this example project: https://github.com/healenium/example_appium_mvn It must solve the problem.

**Comment by aakashr23** [comment]
Hi @alxkor, Thanks for the reply. Sure, I'll check it out.

**Comment by ashish143ti** [comment]
Hi @aakashr23  , could you please send me your Healenium Appium Jar  which you used with your appium test cases , actually I am not able to download Healenium Appium from Maven central Repo . .

It would be great help .
