### ISSUE TITLE
Cannot install repository from bintray

### ISSUE THREAD

**Issue by aproft** [healenium/healenium-appium#22]
Hey guys,

I followed the instructions in the readme, but unfortunately it seems like the dependency got deleted from bintray. When I try to install it via maven, I always get a "403 Forbidden": https://dl.bintray.com/epam/healenium

The one from mvnrepository seems to be broken as well: https://mvnrepository.com/artifact/com.epam.healenium/healenium-appium/1.1
At least when I download and extract it, there's not more than a manifest in there. No classes.

Could you check this? Would love to try out your product. Sounds pretty exciting.

If you need any further information, please let me know.

**Comment by vini46** [comment]
I am stuck with the same problem. Any workaround for this ?

**Comment by genesisthomas** [comment]
Hi @GannaChernyshova, @alxkor, 
JFrog had shutdown [Bintray](https://stackoverflow.com/a/67804820) and I also noticed the same behaviour mentioned by @aproft  
Appium self heal sounds very promising.
Can you please let us know your thoughts/ workarounds on this issue?

**Comment by Alex-Reif** [comment]
Hello everybody,
Sorry for delay, we have relocated to maven central.
Please use 1.2 version from maven central.
