### ISSUE TITLE
Unable to download properly Maven dependency for healenium-appium V1.1

### ISSUE THREAD

**Issue by navinchandrac** [healenium/healenium-appium#23]
Hi,

After adding below maven dependency for healenium-appium V1.1 in POM file for test cases writting.

        <dependency>
            <groupId>com.epam.healenium</groupId>
            <artifactId>healenium-appium</artifactId>
            <version>1.1</version>
        </dependency>

It is showing only MENIFEST.MF file under healenium-appium 1.1.jar file (please refer below screenshot) instead of packages, so due to that unable to **import com.epam.healenium.appium.DriverWrapper** in test cases file for DriverWrapper.wrap class.

![Healenium-Appium](https://user-images.githubusercontent.com/38746974/127490001-095c29bf-e98e-47fa-8380-032bb0d77b43.JPG)

**Comment by ashish143ti** [comment]
I am also facing the same issue , @GannaChernyshova could you please look in to it .

**Comment by Alex-Reif** [comment]
Fixed at 1.2 version.
