### ISSUE TITLE
Getting error in Mac System 

### ISSUE THREAD

**Issue by vaibhavshukl12** [healenium/healenium-appium#38]
Hi Team
,
When I am trying to setup healenium in Mac using docker getting the below error when running docker-compose up

Error-  in mac manifest for helenium/hlm-backend:latest not found: manifest unknown: manifest unknown

But it's working in the Windows system.

**Comment by vaibhavshukl12** [comment]
Hi, @Aliaksei-Ashukha  
Hope you are doing well.
Is there any update on the above issue?

**Comment by Alex-Reif** [comment]
Hi @vaibhavshukl12 
There is no "latest" version of backend image. Actual one is 3.1.5. Please check.

**Comment by vaibhavshukl12** [comment]
Thanks @Aliaksei-Ashukha
