### ISSUE TITLE
NullPointerException whenever trying to find an element with healenium 1.2.2

### ISSUE THREAD

**Issue by lknguyen0** [healenium/healenium-appium#42]
Hi all!

I am trying to use healenium in our project setup and am facing the following problem:
After adding the healenium wrapper, I am getting a NullPointerException and the test steps can not be executed. This happens with healenium version 1.2.2. It works perfectly fine in my setup when using healenium version 1.2 or without the healenium driver wrapper in the same setup. I am using the calculator example on Android. The error occurs whenever I try to find an element, e. g.: 

`        driver.findElement(MobileBy.id("digit_2")).click();
`

Error stack trace: 

`      java.lang.NullPointerException: null value in entry: id=null
	at com.google.common.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:34)
	at com.google.common.collect.SingletonImmutableBiMap.<init>(SingletonImmutableBiMap.java:42)
	at com.google.common.collect.ImmutableBiMap.of(ImmutableBiMap.java:73)
	at com.google.common.collect.ImmutableMap.of(ImmutableMap.java:120)
	at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:84)`

In the following please also find the dependencies and versions I am using in this project:

- Healenium version: 1.2.2
- Healenium backend version: 3.0.8
- Appium version: 1.18.0

I would appreciate any investigation and thanks in advance!

**Comment by Alex-Reif** [comment]
Hi @lknguyen0 , please try actual release version 1.2.3 and actual version of hlm-backend 3.2.1

**Comment by lknguyen0** [comment]
Thanks, it worked out now
